---
- name: Install dependencies
  pacman:
    name:
      - python
      - git
    state: present
  notify:
    - Reload systemd services
  tags:
    - pretalx

- name: Install sqlite
  pacman:
    name:
      - sqlite
    state: present
  notify:
    - Reload systemd services
  when: pretalx_database_backend != 'postgresql' and pretalx_database_backend != 'mysql'
  tags:
    - pretalx

- name: Install redis
  pacman:
    name:
      - redis
    state: present
  notify:
    - Restart redis
  when: pretalx_redis
  tags:
    - pretalx

- name: Start and enable redis
  service:
    name: redis
    state: started
    enabled: true
  when: pretalx_redis
  tags:
    - pretalx
