---
- name: Install dependencies
  pacman:
    name:
      - python
      - git
      - sqlite
      - redis
    state: present
  notify:
    - Reload systemd services
    - Restart redis
  tags:
    - pretalx

- name: Start and enable redis
  service:
    name: redis
    state: started
    enabled: true
  tags:
    - pretalx
