name: Lint

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch: # allows to be run manually

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - 2.7
          - 3.8
          - 3.9
          - 3.10
          - 3.11
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install ansible-lint
        run: pip install --user ansible-lint
      - name: Run ansible-lint
        run: ansible-lint -x ANSIBLE0010 -x 602 .
