name: Lint

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch: # allows to be run manually

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install ansible-lint
        run: pip install --user ansible-lint
      - name: Run ansible-lint
        run: ansible-lint .
